package com.model;

/**
 * Represents a student with basic details.
 */
public class Student {
    private int sid;  // This will be auto-generated by the database
    private String sname;
    private String number;  // Changed to String to match the form field type
    private String password;

    /**
     * Default constructor.
     */
    public Student() {
    }

    /**
     * Parameterized constructor to initialize Student object without ID.
     *
     * @param sname     the student's name
     * @param number    the student's number
     * @param password  the student's password
     */
    public Student(String sname, String number, String password) {
        this.sname = sname;
        this.number = number;
        this.password = password;
    }

    // Getter and Setter for sid
    public int getSid() {
        return sid;
    }

    public void setSid(int sid) {
        this.sid = sid;
    }

    // Getter and Setter for sname
    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    // Getter and Setter for number
    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    // Getter and Setter for password
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "Student [sid=" + sid + ", sname=" + sname + ", number=" + number + ", password=" + password + "]";
    }
}
